/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

API version: 3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vimeoapi

import (
	"encoding/json"
)

// checks if the OnDemandSeasonMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OnDemandSeasonMetadata{}

// OnDemandSeasonMetadata struct for OnDemandSeasonMetadata
type OnDemandSeasonMetadata struct {
	Connections OnDemandSeasonMetadataConnections `json:"connections"`
}

// NewOnDemandSeasonMetadata instantiates a new OnDemandSeasonMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOnDemandSeasonMetadata(connections OnDemandSeasonMetadataConnections) *OnDemandSeasonMetadata {
	this := OnDemandSeasonMetadata{}
	this.Connections = connections
	return &this
}

// NewOnDemandSeasonMetadataWithDefaults instantiates a new OnDemandSeasonMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOnDemandSeasonMetadataWithDefaults() *OnDemandSeasonMetadata {
	this := OnDemandSeasonMetadata{}
	return &this
}

// GetConnections returns the Connections field value
func (o *OnDemandSeasonMetadata) GetConnections() OnDemandSeasonMetadataConnections {
	if o == nil {
		var ret OnDemandSeasonMetadataConnections
		return ret
	}

	return o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value
// and a boolean to check if the value has been set.
func (o *OnDemandSeasonMetadata) GetConnectionsOk() (*OnDemandSeasonMetadataConnections, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connections, true
}

// SetConnections sets field value
func (o *OnDemandSeasonMetadata) SetConnections(v OnDemandSeasonMetadataConnections) {
	o.Connections = v
}

func (o OnDemandSeasonMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OnDemandSeasonMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connections"] = o.Connections
	return toSerialize, nil
}

type NullableOnDemandSeasonMetadata struct {
	value *OnDemandSeasonMetadata
	isSet bool
}

func (v NullableOnDemandSeasonMetadata) Get() *OnDemandSeasonMetadata {
	return v.value
}

func (v *NullableOnDemandSeasonMetadata) Set(val *OnDemandSeasonMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableOnDemandSeasonMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableOnDemandSeasonMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnDemandSeasonMetadata(val *OnDemandSeasonMetadata) *NullableOnDemandSeasonMetadata {
	return &NullableOnDemandSeasonMetadata{value: val, isSet: true}
}

func (v NullableOnDemandSeasonMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnDemandSeasonMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


