/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

API version: 3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vimeoapi

import (
	"encoding/json"
)

// checks if the LiveEventMetadataConnectionsTeamMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LiveEventMetadataConnectionsTeamMember{}

// LiveEventMetadataConnectionsTeamMember Information about the team member who owns the event.
type LiveEventMetadataConnectionsTeamMember struct {
	// An array of the HTTP methods permitted on this URI.
	Options []string `json:"options"`
	// The API URI that resolves to the connection data.
	Uri string `json:"uri"`
}

// NewLiveEventMetadataConnectionsTeamMember instantiates a new LiveEventMetadataConnectionsTeamMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiveEventMetadataConnectionsTeamMember(options []string, uri string) *LiveEventMetadataConnectionsTeamMember {
	this := LiveEventMetadataConnectionsTeamMember{}
	this.Options = options
	this.Uri = uri
	return &this
}

// NewLiveEventMetadataConnectionsTeamMemberWithDefaults instantiates a new LiveEventMetadataConnectionsTeamMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiveEventMetadataConnectionsTeamMemberWithDefaults() *LiveEventMetadataConnectionsTeamMember {
	this := LiveEventMetadataConnectionsTeamMember{}
	return &this
}

// GetOptions returns the Options field value
func (o *LiveEventMetadataConnectionsTeamMember) GetOptions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *LiveEventMetadataConnectionsTeamMember) GetOptionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options, true
}

// SetOptions sets field value
func (o *LiveEventMetadataConnectionsTeamMember) SetOptions(v []string) {
	o.Options = v
}

// GetUri returns the Uri field value
func (o *LiveEventMetadataConnectionsTeamMember) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *LiveEventMetadataConnectionsTeamMember) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *LiveEventMetadataConnectionsTeamMember) SetUri(v string) {
	o.Uri = v
}

func (o LiveEventMetadataConnectionsTeamMember) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LiveEventMetadataConnectionsTeamMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["options"] = o.Options
	toSerialize["uri"] = o.Uri
	return toSerialize, nil
}

type NullableLiveEventMetadataConnectionsTeamMember struct {
	value *LiveEventMetadataConnectionsTeamMember
	isSet bool
}

func (v NullableLiveEventMetadataConnectionsTeamMember) Get() *LiveEventMetadataConnectionsTeamMember {
	return v.value
}

func (v *NullableLiveEventMetadataConnectionsTeamMember) Set(val *LiveEventMetadataConnectionsTeamMember) {
	v.value = val
	v.isSet = true
}

func (v NullableLiveEventMetadataConnectionsTeamMember) IsSet() bool {
	return v.isSet
}

func (v *NullableLiveEventMetadataConnectionsTeamMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiveEventMetadataConnectionsTeamMember(val *LiveEventMetadataConnectionsTeamMember) *NullableLiveEventMetadataConnectionsTeamMember {
	return &NullableLiveEventMetadataConnectionsTeamMember{value: val, isSet: true}
}

func (v NullableLiveEventMetadataConnectionsTeamMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLiveEventMetadataConnectionsTeamMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


