/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

API version: 3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vimeoapi

import (
	"encoding/json"
)

// checks if the AddVideoCreditAlt1Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddVideoCreditAlt1Request{}

// AddVideoCreditAlt1Request struct for AddVideoCreditAlt1Request
type AddVideoCreditAlt1Request struct {
	// The email address of the credited person.
	Email string `json:"email"`
	// The name of the credited person.
	Name string `json:"name"`
	// The role of the credited person.
	Role string `json:"role"`
	// The Vimeo URI of the credited person.
	UserUri string `json:"user_uri"`
}

// NewAddVideoCreditAlt1Request instantiates a new AddVideoCreditAlt1Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddVideoCreditAlt1Request(email string, name string, role string, userUri string) *AddVideoCreditAlt1Request {
	this := AddVideoCreditAlt1Request{}
	this.Email = email
	this.Name = name
	this.Role = role
	this.UserUri = userUri
	return &this
}

// NewAddVideoCreditAlt1RequestWithDefaults instantiates a new AddVideoCreditAlt1Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddVideoCreditAlt1RequestWithDefaults() *AddVideoCreditAlt1Request {
	this := AddVideoCreditAlt1Request{}
	return &this
}

// GetEmail returns the Email field value
func (o *AddVideoCreditAlt1Request) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AddVideoCreditAlt1Request) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AddVideoCreditAlt1Request) SetEmail(v string) {
	o.Email = v
}

// GetName returns the Name field value
func (o *AddVideoCreditAlt1Request) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AddVideoCreditAlt1Request) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AddVideoCreditAlt1Request) SetName(v string) {
	o.Name = v
}

// GetRole returns the Role field value
func (o *AddVideoCreditAlt1Request) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *AddVideoCreditAlt1Request) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *AddVideoCreditAlt1Request) SetRole(v string) {
	o.Role = v
}

// GetUserUri returns the UserUri field value
func (o *AddVideoCreditAlt1Request) GetUserUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserUri
}

// GetUserUriOk returns a tuple with the UserUri field value
// and a boolean to check if the value has been set.
func (o *AddVideoCreditAlt1Request) GetUserUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserUri, true
}

// SetUserUri sets field value
func (o *AddVideoCreditAlt1Request) SetUserUri(v string) {
	o.UserUri = v
}

func (o AddVideoCreditAlt1Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddVideoCreditAlt1Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["name"] = o.Name
	toSerialize["role"] = o.Role
	toSerialize["user_uri"] = o.UserUri
	return toSerialize, nil
}

type NullableAddVideoCreditAlt1Request struct {
	value *AddVideoCreditAlt1Request
	isSet bool
}

func (v NullableAddVideoCreditAlt1Request) Get() *AddVideoCreditAlt1Request {
	return v.value
}

func (v *NullableAddVideoCreditAlt1Request) Set(val *AddVideoCreditAlt1Request) {
	v.value = val
	v.isSet = true
}

func (v NullableAddVideoCreditAlt1Request) IsSet() bool {
	return v.isSet
}

func (v *NullableAddVideoCreditAlt1Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddVideoCreditAlt1Request(val *AddVideoCreditAlt1Request) *NullableAddVideoCreditAlt1Request {
	return &NullableAddVideoCreditAlt1Request{value: val, isSet: true}
}

func (v NullableAddVideoCreditAlt1Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddVideoCreditAlt1Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


