/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

API version: 3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vimeoapi

import (
	"encoding/json"
)

// checks if the ProjectMetadataConnectionsDataRetention type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectMetadataConnectionsDataRetention{}

// ProjectMetadataConnectionsDataRetention struct for ProjectMetadataConnectionsDataRetention
type ProjectMetadataConnectionsDataRetention struct {
	Policy ProjectMetadataConnectionsDataRetentionPolicy `json:"policy"`
}

// NewProjectMetadataConnectionsDataRetention instantiates a new ProjectMetadataConnectionsDataRetention object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectMetadataConnectionsDataRetention(policy ProjectMetadataConnectionsDataRetentionPolicy) *ProjectMetadataConnectionsDataRetention {
	this := ProjectMetadataConnectionsDataRetention{}
	this.Policy = policy
	return &this
}

// NewProjectMetadataConnectionsDataRetentionWithDefaults instantiates a new ProjectMetadataConnectionsDataRetention object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectMetadataConnectionsDataRetentionWithDefaults() *ProjectMetadataConnectionsDataRetention {
	this := ProjectMetadataConnectionsDataRetention{}
	return &this
}

// GetPolicy returns the Policy field value
func (o *ProjectMetadataConnectionsDataRetention) GetPolicy() ProjectMetadataConnectionsDataRetentionPolicy {
	if o == nil {
		var ret ProjectMetadataConnectionsDataRetentionPolicy
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *ProjectMetadataConnectionsDataRetention) GetPolicyOk() (*ProjectMetadataConnectionsDataRetentionPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Policy, true
}

// SetPolicy sets field value
func (o *ProjectMetadataConnectionsDataRetention) SetPolicy(v ProjectMetadataConnectionsDataRetentionPolicy) {
	o.Policy = v
}

func (o ProjectMetadataConnectionsDataRetention) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectMetadataConnectionsDataRetention) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy"] = o.Policy
	return toSerialize, nil
}

type NullableProjectMetadataConnectionsDataRetention struct {
	value *ProjectMetadataConnectionsDataRetention
	isSet bool
}

func (v NullableProjectMetadataConnectionsDataRetention) Get() *ProjectMetadataConnectionsDataRetention {
	return v.value
}

func (v *NullableProjectMetadataConnectionsDataRetention) Set(val *ProjectMetadataConnectionsDataRetention) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectMetadataConnectionsDataRetention) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectMetadataConnectionsDataRetention) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectMetadataConnectionsDataRetention(val *ProjectMetadataConnectionsDataRetention) *NullableProjectMetadataConnectionsDataRetention {
	return &NullableProjectMetadataConnectionsDataRetention{value: val, isSet: true}
}

func (v NullableProjectMetadataConnectionsDataRetention) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectMetadataConnectionsDataRetention) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
