/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

API version: 3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vimeoapi

import (
	"encoding/json"
)

// checks if the OnDemandPromotionMetadataConnections type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OnDemandPromotionMetadataConnections{}

// OnDemandPromotionMetadataConnections A list of resource URIs related to the promotion.
type OnDemandPromotionMetadataConnections struct {
	Codes OnDemandPromotionMetadataConnectionsCodes `json:"codes"`
}

// NewOnDemandPromotionMetadataConnections instantiates a new OnDemandPromotionMetadataConnections object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOnDemandPromotionMetadataConnections(codes OnDemandPromotionMetadataConnectionsCodes) *OnDemandPromotionMetadataConnections {
	this := OnDemandPromotionMetadataConnections{}
	this.Codes = codes
	return &this
}

// NewOnDemandPromotionMetadataConnectionsWithDefaults instantiates a new OnDemandPromotionMetadataConnections object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOnDemandPromotionMetadataConnectionsWithDefaults() *OnDemandPromotionMetadataConnections {
	this := OnDemandPromotionMetadataConnections{}
	return &this
}

// GetCodes returns the Codes field value
func (o *OnDemandPromotionMetadataConnections) GetCodes() OnDemandPromotionMetadataConnectionsCodes {
	if o == nil {
		var ret OnDemandPromotionMetadataConnectionsCodes
		return ret
	}

	return o.Codes
}

// GetCodesOk returns a tuple with the Codes field value
// and a boolean to check if the value has been set.
func (o *OnDemandPromotionMetadataConnections) GetCodesOk() (*OnDemandPromotionMetadataConnectionsCodes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Codes, true
}

// SetCodes sets field value
func (o *OnDemandPromotionMetadataConnections) SetCodes(v OnDemandPromotionMetadataConnectionsCodes) {
	o.Codes = v
}

func (o OnDemandPromotionMetadataConnections) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OnDemandPromotionMetadataConnections) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["codes"] = o.Codes
	return toSerialize, nil
}

type NullableOnDemandPromotionMetadataConnections struct {
	value *OnDemandPromotionMetadataConnections
	isSet bool
}

func (v NullableOnDemandPromotionMetadataConnections) Get() *OnDemandPromotionMetadataConnections {
	return v.value
}

func (v *NullableOnDemandPromotionMetadataConnections) Set(val *OnDemandPromotionMetadataConnections) {
	v.value = val
	v.isSet = true
}

func (v NullableOnDemandPromotionMetadataConnections) IsSet() bool {
	return v.isSet
}

func (v *NullableOnDemandPromotionMetadataConnections) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnDemandPromotionMetadataConnections(val *OnDemandPromotionMetadataConnections) *NullableOnDemandPromotionMetadataConnections {
	return &NullableOnDemandPromotionMetadataConnections{value: val, isSet: true}
}

func (v NullableOnDemandPromotionMetadataConnections) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnDemandPromotionMetadataConnections) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
