/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

API version: 3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vimeoapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VideoMetadataInteractionsEdit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VideoMetadataInteractionsEdit{}

// VideoMetadataInteractionsEdit Information about where and how to edit a video.
type VideoMetadataInteractionsEdit struct {
	// An array of video fields that a user can't interact with.
	BlockedFields []string `json:"blocked_fields"`
	// An array of HTTP methods permitted on this URI.
	Options []string `json:"options"`
	// The API URI that resolves to the connection data.
	Uri string `json:"uri"`
}

type _VideoMetadataInteractionsEdit VideoMetadataInteractionsEdit

// NewVideoMetadataInteractionsEdit instantiates a new VideoMetadataInteractionsEdit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoMetadataInteractionsEdit(blockedFields []string, options []string, uri string) *VideoMetadataInteractionsEdit {
	this := VideoMetadataInteractionsEdit{}
	this.BlockedFields = blockedFields
	this.Options = options
	this.Uri = uri
	return &this
}

// NewVideoMetadataInteractionsEditWithDefaults instantiates a new VideoMetadataInteractionsEdit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoMetadataInteractionsEditWithDefaults() *VideoMetadataInteractionsEdit {
	this := VideoMetadataInteractionsEdit{}
	return &this
}

// GetBlockedFields returns the BlockedFields field value
func (o *VideoMetadataInteractionsEdit) GetBlockedFields() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BlockedFields
}

// GetBlockedFieldsOk returns a tuple with the BlockedFields field value
// and a boolean to check if the value has been set.
func (o *VideoMetadataInteractionsEdit) GetBlockedFieldsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BlockedFields, true
}

// SetBlockedFields sets field value
func (o *VideoMetadataInteractionsEdit) SetBlockedFields(v []string) {
	o.BlockedFields = v
}

// GetOptions returns the Options field value
func (o *VideoMetadataInteractionsEdit) GetOptions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *VideoMetadataInteractionsEdit) GetOptionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options, true
}

// SetOptions sets field value
func (o *VideoMetadataInteractionsEdit) SetOptions(v []string) {
	o.Options = v
}

// GetUri returns the Uri field value
func (o *VideoMetadataInteractionsEdit) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *VideoMetadataInteractionsEdit) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *VideoMetadataInteractionsEdit) SetUri(v string) {
	o.Uri = v
}

func (o VideoMetadataInteractionsEdit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VideoMetadataInteractionsEdit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["blocked_fields"] = o.BlockedFields
	toSerialize["options"] = o.Options
	toSerialize["uri"] = o.Uri
	return toSerialize, nil
}

func (o *VideoMetadataInteractionsEdit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"blocked_fields",
		"options",
		"uri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVideoMetadataInteractionsEdit := _VideoMetadataInteractionsEdit{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVideoMetadataInteractionsEdit)

	if err != nil {
		return err
	}

	*o = VideoMetadataInteractionsEdit(varVideoMetadataInteractionsEdit)

	return err
}

type NullableVideoMetadataInteractionsEdit struct {
	value *VideoMetadataInteractionsEdit
	isSet bool
}

func (v NullableVideoMetadataInteractionsEdit) Get() *VideoMetadataInteractionsEdit {
	return v.value
}

func (v *NullableVideoMetadataInteractionsEdit) Set(val *VideoMetadataInteractionsEdit) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoMetadataInteractionsEdit) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoMetadataInteractionsEdit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoMetadataInteractionsEdit(val *VideoMetadataInteractionsEdit) *NullableVideoMetadataInteractionsEdit {
	return &NullableVideoMetadataInteractionsEdit{value: val, isSet: true}
}

func (v NullableVideoMetadataInteractionsEdit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoMetadataInteractionsEdit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


