/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

API version: 3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vimeoapi

import (
	"encoding/json"
)

// checks if the VideoMetadataInteractionsEditPrivacy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VideoMetadataInteractionsEditPrivacy{}

// VideoMetadataInteractionsEditPrivacy Information about editing the privacy of the video.
type VideoMetadataInteractionsEditPrivacy struct {
	// A list of valid content rating flags for the video.
	ContentRating []string `json:"content_rating"`
	// An array of HTTP methods permitted on this URI.
	Options []string `json:"options"`
	// An array of suggested fields to be used for this interaction.
	Properties []VideoMetadataInteractionsEditPrivacyPropertiesInner `json:"properties"`
	// The API URI that resolves to the connection data.
	Uri string `json:"uri"`
}

// NewVideoMetadataInteractionsEditPrivacy instantiates a new VideoMetadataInteractionsEditPrivacy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoMetadataInteractionsEditPrivacy(contentRating []string, options []string, properties []VideoMetadataInteractionsEditPrivacyPropertiesInner, uri string) *VideoMetadataInteractionsEditPrivacy {
	this := VideoMetadataInteractionsEditPrivacy{}
	this.ContentRating = contentRating
	this.Options = options
	this.Properties = properties
	this.Uri = uri
	return &this
}

// NewVideoMetadataInteractionsEditPrivacyWithDefaults instantiates a new VideoMetadataInteractionsEditPrivacy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoMetadataInteractionsEditPrivacyWithDefaults() *VideoMetadataInteractionsEditPrivacy {
	this := VideoMetadataInteractionsEditPrivacy{}
	return &this
}

// GetContentRating returns the ContentRating field value
func (o *VideoMetadataInteractionsEditPrivacy) GetContentRating() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ContentRating
}

// GetContentRatingOk returns a tuple with the ContentRating field value
// and a boolean to check if the value has been set.
func (o *VideoMetadataInteractionsEditPrivacy) GetContentRatingOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContentRating, true
}

// SetContentRating sets field value
func (o *VideoMetadataInteractionsEditPrivacy) SetContentRating(v []string) {
	o.ContentRating = v
}

// GetOptions returns the Options field value
func (o *VideoMetadataInteractionsEditPrivacy) GetOptions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *VideoMetadataInteractionsEditPrivacy) GetOptionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options, true
}

// SetOptions sets field value
func (o *VideoMetadataInteractionsEditPrivacy) SetOptions(v []string) {
	o.Options = v
}

// GetProperties returns the Properties field value
func (o *VideoMetadataInteractionsEditPrivacy) GetProperties() []VideoMetadataInteractionsEditPrivacyPropertiesInner {
	if o == nil {
		var ret []VideoMetadataInteractionsEditPrivacyPropertiesInner
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *VideoMetadataInteractionsEditPrivacy) GetPropertiesOk() ([]VideoMetadataInteractionsEditPrivacyPropertiesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Properties, true
}

// SetProperties sets field value
func (o *VideoMetadataInteractionsEditPrivacy) SetProperties(v []VideoMetadataInteractionsEditPrivacyPropertiesInner) {
	o.Properties = v
}

// GetUri returns the Uri field value
func (o *VideoMetadataInteractionsEditPrivacy) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *VideoMetadataInteractionsEditPrivacy) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *VideoMetadataInteractionsEditPrivacy) SetUri(v string) {
	o.Uri = v
}

func (o VideoMetadataInteractionsEditPrivacy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VideoMetadataInteractionsEditPrivacy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content_rating"] = o.ContentRating
	toSerialize["options"] = o.Options
	toSerialize["properties"] = o.Properties
	toSerialize["uri"] = o.Uri
	return toSerialize, nil
}

type NullableVideoMetadataInteractionsEditPrivacy struct {
	value *VideoMetadataInteractionsEditPrivacy
	isSet bool
}

func (v NullableVideoMetadataInteractionsEditPrivacy) Get() *VideoMetadataInteractionsEditPrivacy {
	return v.value
}

func (v *NullableVideoMetadataInteractionsEditPrivacy) Set(val *VideoMetadataInteractionsEditPrivacy) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoMetadataInteractionsEditPrivacy) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoMetadataInteractionsEditPrivacy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoMetadataInteractionsEditPrivacy(val *VideoMetadataInteractionsEditPrivacy) *NullableVideoMetadataInteractionsEditPrivacy {
	return &NullableVideoMetadataInteractionsEditPrivacy{value: val, isSet: true}
}

func (v NullableVideoMetadataInteractionsEditPrivacy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoMetadataInteractionsEditPrivacy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
