/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

API version: 3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vimeoapi

import (
	"encoding/json"
)

// checks if the TrimmedVideoMetadataConnections type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrimmedVideoMetadataConnections{}

// TrimmedVideoMetadataConnections struct for TrimmedVideoMetadataConnections
type TrimmedVideoMetadataConnections struct {
	CreatedVersion TrimmedVideoMetadataConnectionsCreatedVersion `json:"created_version"`
	RootVersion    TrimmedVideoMetadataConnectionsRootVersion    `json:"root_version"`
	Video          TrimmedVideoMetadataConnectionsVideo          `json:"video"`
}

// NewTrimmedVideoMetadataConnections instantiates a new TrimmedVideoMetadataConnections object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrimmedVideoMetadataConnections(createdVersion TrimmedVideoMetadataConnectionsCreatedVersion, rootVersion TrimmedVideoMetadataConnectionsRootVersion, video TrimmedVideoMetadataConnectionsVideo) *TrimmedVideoMetadataConnections {
	this := TrimmedVideoMetadataConnections{}
	this.CreatedVersion = createdVersion
	this.RootVersion = rootVersion
	this.Video = video
	return &this
}

// NewTrimmedVideoMetadataConnectionsWithDefaults instantiates a new TrimmedVideoMetadataConnections object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrimmedVideoMetadataConnectionsWithDefaults() *TrimmedVideoMetadataConnections {
	this := TrimmedVideoMetadataConnections{}
	return &this
}

// GetCreatedVersion returns the CreatedVersion field value
func (o *TrimmedVideoMetadataConnections) GetCreatedVersion() TrimmedVideoMetadataConnectionsCreatedVersion {
	if o == nil {
		var ret TrimmedVideoMetadataConnectionsCreatedVersion
		return ret
	}

	return o.CreatedVersion
}

// GetCreatedVersionOk returns a tuple with the CreatedVersion field value
// and a boolean to check if the value has been set.
func (o *TrimmedVideoMetadataConnections) GetCreatedVersionOk() (*TrimmedVideoMetadataConnectionsCreatedVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedVersion, true
}

// SetCreatedVersion sets field value
func (o *TrimmedVideoMetadataConnections) SetCreatedVersion(v TrimmedVideoMetadataConnectionsCreatedVersion) {
	o.CreatedVersion = v
}

// GetRootVersion returns the RootVersion field value
func (o *TrimmedVideoMetadataConnections) GetRootVersion() TrimmedVideoMetadataConnectionsRootVersion {
	if o == nil {
		var ret TrimmedVideoMetadataConnectionsRootVersion
		return ret
	}

	return o.RootVersion
}

// GetRootVersionOk returns a tuple with the RootVersion field value
// and a boolean to check if the value has been set.
func (o *TrimmedVideoMetadataConnections) GetRootVersionOk() (*TrimmedVideoMetadataConnectionsRootVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RootVersion, true
}

// SetRootVersion sets field value
func (o *TrimmedVideoMetadataConnections) SetRootVersion(v TrimmedVideoMetadataConnectionsRootVersion) {
	o.RootVersion = v
}

// GetVideo returns the Video field value
func (o *TrimmedVideoMetadataConnections) GetVideo() TrimmedVideoMetadataConnectionsVideo {
	if o == nil {
		var ret TrimmedVideoMetadataConnectionsVideo
		return ret
	}

	return o.Video
}

// GetVideoOk returns a tuple with the Video field value
// and a boolean to check if the value has been set.
func (o *TrimmedVideoMetadataConnections) GetVideoOk() (*TrimmedVideoMetadataConnectionsVideo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Video, true
}

// SetVideo sets field value
func (o *TrimmedVideoMetadataConnections) SetVideo(v TrimmedVideoMetadataConnectionsVideo) {
	o.Video = v
}

func (o TrimmedVideoMetadataConnections) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrimmedVideoMetadataConnections) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_version"] = o.CreatedVersion
	toSerialize["root_version"] = o.RootVersion
	toSerialize["video"] = o.Video
	return toSerialize, nil
}

type NullableTrimmedVideoMetadataConnections struct {
	value *TrimmedVideoMetadataConnections
	isSet bool
}

func (v NullableTrimmedVideoMetadataConnections) Get() *TrimmedVideoMetadataConnections {
	return v.value
}

func (v *NullableTrimmedVideoMetadataConnections) Set(val *TrimmedVideoMetadataConnections) {
	v.value = val
	v.isSet = true
}

func (v NullableTrimmedVideoMetadataConnections) IsSet() bool {
	return v.isSet
}

func (v *NullableTrimmedVideoMetadataConnections) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrimmedVideoMetadataConnections(val *TrimmedVideoMetadataConnections) *NullableTrimmedVideoMetadataConnections {
	return &NullableTrimmedVideoMetadataConnections{value: val, isSet: true}
}

func (v NullableTrimmedVideoMetadataConnections) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrimmedVideoMetadataConnections) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
