/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

API version: 3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vimeoapi

import (
	"encoding/json"
)

// checks if the AlbumMetadataInteractionsAddTo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlbumMetadataInteractionsAddTo{}

// AlbumMetadataInteractionsAddTo Information about adding or removing a video from the showcase. This data requires a bearer token with the `private` scope.
type AlbumMetadataInteractionsAddTo struct {
	// An array of HTTP methods permitted on this URI. This data requires a bearer token with the `private` scope.
	Options []string `json:"options"`
	// The API URI that resolves to the connection data. This data requires a bearer token with the `private` scope.
	Uri string `json:"uri"`
}

// NewAlbumMetadataInteractionsAddTo instantiates a new AlbumMetadataInteractionsAddTo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlbumMetadataInteractionsAddTo(options []string, uri string) *AlbumMetadataInteractionsAddTo {
	this := AlbumMetadataInteractionsAddTo{}
	this.Options = options
	this.Uri = uri
	return &this
}

// NewAlbumMetadataInteractionsAddToWithDefaults instantiates a new AlbumMetadataInteractionsAddTo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlbumMetadataInteractionsAddToWithDefaults() *AlbumMetadataInteractionsAddTo {
	this := AlbumMetadataInteractionsAddTo{}
	return &this
}

// GetOptions returns the Options field value
func (o *AlbumMetadataInteractionsAddTo) GetOptions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *AlbumMetadataInteractionsAddTo) GetOptionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options, true
}

// SetOptions sets field value
func (o *AlbumMetadataInteractionsAddTo) SetOptions(v []string) {
	o.Options = v
}

// GetUri returns the Uri field value
func (o *AlbumMetadataInteractionsAddTo) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *AlbumMetadataInteractionsAddTo) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *AlbumMetadataInteractionsAddTo) SetUri(v string) {
	o.Uri = v
}

func (o AlbumMetadataInteractionsAddTo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlbumMetadataInteractionsAddTo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["options"] = o.Options
	toSerialize["uri"] = o.Uri
	return toSerialize, nil
}

type NullableAlbumMetadataInteractionsAddTo struct {
	value *AlbumMetadataInteractionsAddTo
	isSet bool
}

func (v NullableAlbumMetadataInteractionsAddTo) Get() *AlbumMetadataInteractionsAddTo {
	return v.value
}

func (v *NullableAlbumMetadataInteractionsAddTo) Set(val *AlbumMetadataInteractionsAddTo) {
	v.value = val
	v.isSet = true
}

func (v NullableAlbumMetadataInteractionsAddTo) IsSet() bool {
	return v.isSet
}

func (v *NullableAlbumMetadataInteractionsAddTo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlbumMetadataInteractionsAddTo(val *AlbumMetadataInteractionsAddTo) *NullableAlbumMetadataInteractionsAddTo {
	return &NullableAlbumMetadataInteractionsAddTo{value: val, isSet: true}
}

func (v NullableAlbumMetadataInteractionsAddTo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlbumMetadataInteractionsAddTo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


