/*
Vimeo API

Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

API version: 3.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vimeoapi

import (
	"encoding/json"
)

// checks if the CaptureWebinarRegistrationListAlt1Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CaptureWebinarRegistrationListAlt1Request{}

// CaptureWebinarRegistrationListAlt1Request struct for CaptureWebinarRegistrationListAlt1Request
type CaptureWebinarRegistrationListAlt1Request struct {
	// An array of registration data for the webinar.
	Registrants []CaptureWebinarRegistrationListAlt1RequestRegistrantsInner `json:"registrants,omitempty"`
}

// NewCaptureWebinarRegistrationListAlt1Request instantiates a new CaptureWebinarRegistrationListAlt1Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaptureWebinarRegistrationListAlt1Request() *CaptureWebinarRegistrationListAlt1Request {
	this := CaptureWebinarRegistrationListAlt1Request{}
	return &this
}

// NewCaptureWebinarRegistrationListAlt1RequestWithDefaults instantiates a new CaptureWebinarRegistrationListAlt1Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaptureWebinarRegistrationListAlt1RequestWithDefaults() *CaptureWebinarRegistrationListAlt1Request {
	this := CaptureWebinarRegistrationListAlt1Request{}
	return &this
}

// GetRegistrants returns the Registrants field value if set, zero value otherwise.
func (o *CaptureWebinarRegistrationListAlt1Request) GetRegistrants() []CaptureWebinarRegistrationListAlt1RequestRegistrantsInner {
	if o == nil || IsNil(o.Registrants) {
		var ret []CaptureWebinarRegistrationListAlt1RequestRegistrantsInner
		return ret
	}
	return o.Registrants
}

// GetRegistrantsOk returns a tuple with the Registrants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptureWebinarRegistrationListAlt1Request) GetRegistrantsOk() ([]CaptureWebinarRegistrationListAlt1RequestRegistrantsInner, bool) {
	if o == nil || IsNil(o.Registrants) {
		return nil, false
	}
	return o.Registrants, true
}

// HasRegistrants returns a boolean if a field has been set.
func (o *CaptureWebinarRegistrationListAlt1Request) HasRegistrants() bool {
	if o != nil && !IsNil(o.Registrants) {
		return true
	}

	return false
}

// SetRegistrants gets a reference to the given []CaptureWebinarRegistrationListAlt1RequestRegistrantsInner and assigns it to the Registrants field.
func (o *CaptureWebinarRegistrationListAlt1Request) SetRegistrants(v []CaptureWebinarRegistrationListAlt1RequestRegistrantsInner) {
	o.Registrants = v
}

func (o CaptureWebinarRegistrationListAlt1Request) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CaptureWebinarRegistrationListAlt1Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Registrants) {
		toSerialize["registrants"] = o.Registrants
	}
	return toSerialize, nil
}

type NullableCaptureWebinarRegistrationListAlt1Request struct {
	value *CaptureWebinarRegistrationListAlt1Request
	isSet bool
}

func (v NullableCaptureWebinarRegistrationListAlt1Request) Get() *CaptureWebinarRegistrationListAlt1Request {
	return v.value
}

func (v *NullableCaptureWebinarRegistrationListAlt1Request) Set(val *CaptureWebinarRegistrationListAlt1Request) {
	v.value = val
	v.isSet = true
}

func (v NullableCaptureWebinarRegistrationListAlt1Request) IsSet() bool {
	return v.isSet
}

func (v *NullableCaptureWebinarRegistrationListAlt1Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaptureWebinarRegistrationListAlt1Request(val *CaptureWebinarRegistrationListAlt1Request) *NullableCaptureWebinarRegistrationListAlt1Request {
	return &NullableCaptureWebinarRegistrationListAlt1Request{value: val, isSet: true}
}

func (v NullableCaptureWebinarRegistrationListAlt1Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCaptureWebinarRegistrationListAlt1Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
